# Generated by Django 5.2.3 on 2025-07-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0003_alter_invoice_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='name',
            new_name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='grand_total',
        ),
        migrations.AddField(
            model_name='invoice',
            name='grand_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total_amount',
            field=models.IntegerField(blank=True),
        ),
    ]
