# Generated by Django 5.2.3 on 2025-07-21 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0004_rename_name_invoiceitem_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='dates',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
