# Generated by Django 5.2.3 on 2025-07-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0005_invoiceitem_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
